using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class ColorMaterial
{
    public string ColorName;
    public Material JointsColor;
    public Material SurfaceColor;
}
[System.Serializable]
public class PlayerParticle
{
    public string ParticleName;
    public ParticleSystem particleSystem;
}

public class CloakSystem : MonoBehaviour
{
    public enum Color
    {
        SΤP方=0,
        酽猬P方=1,
        屡猬P方=2,
        厚猬P方=3,
    }
    [Header("ゆOB")]
    public int SpaceNumber;
    [SerializeField]
    private GameObject[] PlayerChild;
    private PlayerState playerState;


    [Header("1腹 ゆO逆")]
    public bool Space1;
    public Color Space1Color;
    [Header("2腹 ゆO逆")]
    public bool Space2;
    public Color Space2Color;
    [Header("P方ち传")]
    [SerializeField]
    private float MaxQCD;
    private float QCD;
    [Header("P方メY")]
    [SerializeField]
    private GameObject[] Star;
    [SerializeField]
    private float Speed;
    [SerializeField]
    private float SpeedUp;
    
    [SerializeField]
    private float OnetypeSensitivity;
    

    /*
    [Header("ブ涧C")]
    [SerializeField]
    private Renderer PlayerJoints;
    [SerializeField]
    private Renderer PlayerSurface;
    [SerializeField]
    private ColorMaterial[] Material;
    */
    [Header("S")]
    [SerializeField]
    private PlayerParticle[] Particle;

    private void Start()
    {
        playerState = GameMannager.gameMannager.playerState;
        int childNumber = transform.childCount;
        PlayerChild = new GameObject[childNumber];
        for (int i = 0; i < childNumber;i++)
        {
            PlayerChild[i] = this.transform.GetChild(i).gameObject;
        }
    }
    private void Update()
    {
        UIupdate();
        SwitchSystem();
    }

    private void SwitchSystem()
    {
        if (Input.GetKeyDown(KeyCode.F))
        {
            ThorwStar();
        }
        if (Input.GetKeyDown(KeyCode.Q))
        {
            QCD = 0;
        }

        if (Input.GetKey(KeyCode.Q))
        {
            Debug.Log("Q龅");
            QCD += Time.deltaTime;
        }
        else
        if (Input.GetKeyUp(KeyCode.Q)) 
        {
            Debug.Log("Q穸}");
            if (QCD < OnetypeSensitivity) 
            {
                if (SpaceNumber == 0)
                {
                    if(Space1Color == Color.SΤP方)
                    {
                        Debug.Log("Noting can switch");
                    }else
                    {
                        Debug.Log("ち传1腹ゆO逆");
                        SpaceNumber = 1;
                        SwitchColor(1);
                    }
                }
                else
                if (SpaceNumber == 1) 
                {
                    Debug.Log("ち传2腹ゆO逆");
                    SpaceNumber = 2;
                    SwitchColor(2);
                }
                else
                if (SpaceNumber == 2)
                {
                    Debug.Log("ち传1腹ゆO逆");
                    SpaceNumber = 1;
                    SwitchColor(1);
                }
                else
                {
                    Debug.Log("{ΑX岿");
                }
            }
            if (QCD > MaxQCD)
            {
                Debug.Log("齑_娄猡媪O");
                SpaceNumber = 0;
                SwitchColor(0);
            }
        }
    }
    private void ThorwStar()
    {
        if (SpaceNumber == 0)
        {
            Debug.Log("Noting Can Thorw");
        } else
        {
            //ネΘ@聋P方A琵ウ┕e弗XhA碑a齑_Θフ猡媪OC
            Vector3 ShootingPosition = this.transform.position + this.transform.forward * 2 + this.transform.up * 2;
            GameObject TossedStar = null;

            if (SpaceNumber == 1)
            {
                if (Space1Color != Color.SΤP方)
                {
                    GameObject tossedStar = Instantiate(Star[(int)Space1Color], ShootingPosition, this.transform.rotation);
                    TossedStar = tossedStar;
                    playerState.DurabilitySystem(1, "Lose");

                    Color temporaryColor = Space2Color;
                    bool temporarySpace = Space2;
                    Space2Color = Color.SΤP方;
                    Space2 = false;
                    Space1Color = temporaryColor;
                    SwitchColor(1);
                    Space1 = temporarySpace;

                    /*
                    bool tempoaryActivity = playerState.Activity_2;
                    float temporaryDurability = playerState.Durability_2;
                    playerState.DurabilitySystem(2, "Lose");
                    playerState.Activity_1 = tempoaryActivity;
                    playerState.Durability_1 = temporaryDurability;
                    */
                }
                else Debug.Log("Noting can throw");
            }
            else
            if (SpaceNumber == 2)
            {
                if (Space2Color != Color.SΤP方)
                {
                    GameObject tossedStar = Instantiate(Star[(int)Space2Color], ShootingPosition, this.transform.rotation);
                    TossedStar = tossedStar;
                    playerState.DurabilitySystem(2, "Lose");

                    Space2Color = Color.SΤP方;
                    SwitchColor(2);
                    Space2 = false;
                }
                else Debug.Log("Noting can thorw");
            }
            Rigidbody StarRigid = TossedStar.GetComponent<Rigidbody>();
            Vector3 Direction = this.transform.forward;
            Vector3 DirectoinUp = this.transform.up;
            StarRigid.velocity = Direction * Speed + DirectoinUp * SpeedUp;
            Debug.Log("碑a齑_哎咋猡媪O");
            SpaceNumber = 0;
        }
    }
    public void SwitchColor(int SpaceNumber)
    {
        switch(SpaceNumber)
        {
            case 0:
                Debug.Log("ち传Θη");
                SwitchParticle(0);
                SwitchLayers(0);
                break;
            case 1:
                if (Space1)
                {
                    Debug.Log("ち传Θ@腹烀C");

                    /*
                    PlayerJoints.sharedMaterial = Material[(int)Space1Color].JointsColor;
                    PlayerSurface.sharedMaterial = Material[(int)Space1Color].SurfaceColor;
                    */

                    SwitchParticle((int)Space1Color);
                    SwitchLayers((int)Space1Color);
                }else SwitchColor(0);
                break;
            case 2:
                if (SpaceNumber == 2)
                {
                    if (Space2)
                    {
                        Debug.Log("ち传Θ@腹烀C");
                        SwitchParticle((int)Space2Color);
                        SwitchLayers((int)Space2Color);
                    }else SwitchColor(0);
                }
                break;
            default:
                if (SpaceNumber > 2) Debug.Log("{Α岿~");
                break;
        }
    }
    private void SwitchParticle(int index)
    {
        if (index == 0)
        {
            Particle[0].particleSystem.gameObject.SetActive(true);
            Particle[1].particleSystem.gameObject.SetActive(false);
            Particle[2].particleSystem.gameObject.SetActive(false);
            Particle[3].particleSystem.gameObject.SetActive(false);
        }
        if (index == 1)
        {
            Particle[0].particleSystem.gameObject.SetActive(false);
            Particle[1].particleSystem.gameObject.SetActive(true);
            Particle[2].particleSystem.gameObject.SetActive(false);
            Particle[3].particleSystem.gameObject.SetActive(false);
        }
        if (index == 2)
        {
            Particle[0].particleSystem.gameObject.SetActive(false);
            Particle[1].particleSystem.gameObject.SetActive(false);
            Particle[2].particleSystem.gameObject.SetActive(true);
            Particle[3].particleSystem.gameObject.SetActive(false);
        }
        if (index == 3)
        {
            Particle[0].particleSystem.gameObject.SetActive(false);
            Particle[1].particleSystem.gameObject.SetActive(false);
            Particle[2].particleSystem.gameObject.SetActive(false);
            Particle[3].particleSystem.gameObject.SetActive(true);
        }
    }
    private void SwitchLayers(int Color)
    {
        int childNumber = transform.childCount;
        switch (Color)
        {
            case 0:
                Debug.Log("ち传哎咋 Layers");
                this.gameObject.layer = 7;
                for (int i = 0; i < childNumber; i++)
                {
                    PlayerChild[i].gameObject.layer = 7;     
                }
                break;
            case 1:
                Debug.Log("ち传艾酽 Layers");
                this.gameObject.layer = 8;
                for (int i = 0; i < childNumber; i++)
                {
                    PlayerChild[i].gameObject.layer = 8;
                }
                break;
            case 2:
                Debug.Log("ち传奥纽 Layers");
                this.gameObject.layer = 9;
                for (int i = 0; i < childNumber; i++)
                {
                    PlayerChild[i].gameObject.layer = 9;
                }
                break;
            case 3:
                Debug.Log("ち传昂瘭 Layers");
                this.gameObject.layer = 10;
                for (int i = 0; i < childNumber; i++)
                {
                    PlayerChild[i].gameObject.layer = 10;
                }
                break;
        }
    }
    private void UIupdate()
    {
        if (Space1 == true)
        {

        }
        if (Space2 == true)
        {

        }
    }
}
