using System.Collections;
using System.Collections.Generic;
using UnityEngine;
public class Star : MonoBehaviour
{
    private enum Color
    {
        SΤP方 = 0,
        酽猬P方 = 1,
        屡猬P方 = 2,
        厚猬P方 = 3,
    }
    private Animator animator;
    private CloakSystem CloakSystem;
    private PlayerState StateSystem;
    private UIMannager UImannager;
    [SerializeField]
    private CloakSystem.Color thisColor;
    [SerializeField]
    private float floatingFroce;
    private void Start()
    {
        animator = GetComponent<Animator>();
        CloakSystem = GameMannager.gameMannager.cloakSystem;
        StateSystem = GameMannager.gameMannager.playerState;
        UImannager = GameMannager.gameMannager.UImannager;
    }

    private void OnCollisionEnter(Collision other)
    {
        Debug.Log("Trigggggggggggggggggggger");
        if (other.gameObject.tag == "Player")
        {
            animator.Play("GetStar");
            Debug.Log("碑aI飕P方");

            if (CloakSystem.Space1 == false)
            {
                Debug.Log("1腹哦〃o宫P方");
                CloakSystem.Space1Color = thisColor;
                CloakSystem.Space1 = true;
                StateSystem.DurabilitySystem(1,"Get");
                UImannager.SwitchCloakBarColor();
            }
            else
            if (CloakSystem.Space1Color == thisColor)
            {
                Debug.Log("干R1腹哦―含P方喽q");
            }
            else
            if (CloakSystem.Space2 == false) 
            {
                Debug.Log("2腹哦〃o宫P方");
                CloakSystem.Space2Color = thisColor;
                CloakSystem.Space2 = true;
                StateSystem.DurabilitySystem(2,"Get");
                UImannager.SwitchCloakBarColor();
            }
            else
            if(CloakSystem.Space2Color==thisColor)
            {
                Debug.Log("干R2腹哦―含P方喽q");
            }else
            {
                Debug.Log("P方|犯");
            }
            
        }else
        {
            
        }
    }
    
    public void DestroyStar()
    {
        Destroy(this.animator.gameObject);
    }
    private void floating()
    {
        //nouse;
        Rigidbody rigid = this.GetComponent<Rigidbody>();
        Vector3 force = new Vector3(0, floatingFroce, 0);
        rigid.AddForce(force, ForceMode.Force);
        Debug.Log("Forceeee");
    }
}
